---

- name: billow
  hosts: tag_amibuilder_billow
  tags:
  - billow
  roles:
  - base
  - billow
  user: "{{site.base_user}}"
  sudo: true

- name: wrathofchris
  hosts: tag_amibuilder_wrathofchris
  tags:
  - wrathofchris
  roles:
  - base
  - billow
  - wrathofchris
  user: "{{site.base_user}}"
  sudo: true
